name: Multiple jobs execution

on: push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              
            - name: Install cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute ASCII using cowsay
              run : cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.txt


    test_job_2:
         needs: build_job_1
         runs-on: ubuntu-latest                      
         steps:     
            - name: Test if file exists
              run: grep -i "dragon" dragon.txt


    deploy-job-3:
           needs: test_job_2
           runs-on: ubuntu-latest
           steps:
            - name: Read file
              run: cat dragon.txt
              
            - name: Deployment
              run: echo Deploying 