name: Program for ASCII generation

on: push

jobs:
    ascii_job:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4

            - name: List files
              run:  ls -lart
              
            - name: Execute Shell script
              run: |
                chmod +x ascii-scripts.sh    
                ./ascii-scripts.sh
              