name: My first Github Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Message
              uses: actions/checkout@v4

            - name: List files
              run: ls

            - name : Files contents
              run: cat README.md
            