name: My first Github Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Message
              uses: actions/checkout@v4

            - name: List and Read files
              run: |
                   echo "My first github actions file"
                   ls -lart
                   cat README.md

            # - name : Third Party Library
            #   run: cowsay -f dragon "Run for cover, I am a DRAGON....RAWR" >> dragon.xt
            