name: Test Workflow dispatch

on:
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        type:
          description: 'Type level'
          required: true
          default: 'warning'
          type: choice
          options:
          - abc
          - fdg
          - tis 


jobs:
    test_my_inputs:
     runs-on: ubuntu   
     steps:
        - run: |
            echo "Workflow dispact is pass" 
        
          
               